[versions]
agp = "8.11.0"
cameraCore = "1.4.2"
cameraCamera2 = "1.4.2"
cameraExtensions = "1.4.2"
gson = "2.13.1"
json = "20250517"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.1"
zebraAIVisionSdk = "3.0.5"
barcodeLocalizer = "5.0.1"
criticalpermissionhelper = "0.8.1"
datawedgeintentwrapper = "14.10"
poi = "5.2.3"
poi-ooxml = "5.2.3"

[libraries]
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraExtensions" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
barcode-localizer = { group = "com.zebra.ai.models", name = "barcode-localizer", version.ref = "barcodeLocalizer" }
zebra-ai-vision-sdk = { group = "com.zebra.ai.vision", name = "AI-Data-Capture-SDK", version.ref = "zebraAIVisionSdk" }
criticalpermissionhelper =  { group = "com.github.ltrudu", name = "CriticalPermissionsHelper", version.ref = "criticalpermissionhelper" }
datawedgeintentwrapper =  { group = "com.github.ltrudu", name = "DataWedgeIntentWrapper", version.ref = "datawedgeintentwrapper" }
poi =  { group = "org.apache.poi", name = "poi", version.ref = "poi" }
poiooxml =  { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi-ooxml" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }


